config/routes.rb
Rails.application.routes.draw do
  get 'news/news'

  get 'gallery/gallery'

  get 'contact/contact'

  get 'about/about'

  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def about
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def contact
  end
end

app/controllers/gallery_controller.rb
class GalleryController < ApplicationController
  def gallery
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  def news
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/gallery_helper.rb
module GalleryHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/about/about.html.erb
<!-- about -->
<!-- who we are -->
<div class="who-are">
	<div class="container">
		<h3 class="tittle">About</h3>
		<div class="col-md-7 abt-left wow fadeInRight animated" data-wow-delay=".5s">
			<div class="about-img">
				<a href="single.html"><%= image_tag("g1.jpg" ,:class => "img-responsive", :alt => " ") %></a>
			</div>
			<div class="about-img">
				<a href="single.html"><%= image_tag("g2.jpg" ,:class => "img-responsive", :alt => " ") %></a>
			</div>
			<div class="about-img">
				<a href="single.html"><%= image_tag("g4.jpg" ,:class => "img-responsive", :alt => " ") %></a>			
			</div>
			<div class="clearfix"></div>
		</div>
		<div class="col-md-5 abt-right wow fadeInLeft animated" data-wow-delay=".5s">
			<h4>Voluptatem quia voluptas sit </h4>
			<p>Nemo enim ipsam voluptatem quia 
			voluptas sit aspernatur aut odit aut fugit, 
			sed quia consequuntur magni dolores eos qui 
			ratione voluptatem sequi nesciunt. Nemo enim ipsam voluptatem quia 
			voluptas sit aspernatur aut odit aut fugit, 
			sed quia consequuntur magni dolores eos qui 
			ratione voluptatem sequi nesciunt.</p>
			<p>
			Nemo enim ipsam voluptatem quia voluptas
			sit aspernatur aut odit aut fugit, sed quia 
			consequuntur magni dolore.</p>
		</div>
		<div class="clearfix"></div>
	</div>
</div>
<!-- //who we are -->
<div class="whychoose">
				<div class="container">
					<h3 class="tittle">why choose us</h3>
					<div class="choose-grids">
						<div class="col-md-4 choose-grid wow fadeInRight animated" data-wow-delay=".5s">
						<h4><span class="glyphicon glyphicon-user" aria-hidden="true"></span>Nam aliquam pretium</h4>
						<p>Aenean ac leo eget nunc fringilla fringilla a non nulla! Nunc orci mi, venenatis quis ultrices vitae, congue non nibh. Nulla bibendum justo eget.</p>
						</div>
						<div class="col-md-4 choose-grid wow fadeInRight animated" data-wow-delay=".5s">
						<h4><span class="glyphicon glyphicon-lock" aria-hidden="true"></span>Nam aliquam pretium</h4>
						<p>Aenean ac leo eget nunc fringilla fringilla a non nulla! Nunc orci mi, venenatis quis ultrices vitae, congue non nibh. Nulla bibendum justo eget.</p>
						</div>
						<div class="col-md-4 choose-grid wow fadeInRight animated" data-wow-delay=".5s">
						<h4><span class="glyphicon glyphicon-book" aria-hidden="true"></span>Nam aliquam pretium</h4>
						<p>Aenean ac leo eget nunc fringilla fringilla a non nulla! Nunc orci mi, venenatis quis ultrices vitae, congue non nibh. Nulla bibendum justo eget.</p>
						</div>
						<div class="col-md-4 choose-grid wow fadeInLeft animated" data-wow-delay=".5s">
						<h4><span class="glyphicon glyphicon-home" aria-hidden="true"></span>Nam aliquam pretium</h4>
						<p>Aenean ac leo eget nunc fringilla fringilla a non nulla! Nunc orci mi, venenatis quis ultrices vitae, congue non nibh. Nulla bibendum justo eget.</p>
						</div>
						<div class="col-md-4 choose-grid wow fadeInLeft animated" data-wow-delay=".5s">
						<h4><span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span>Nam aliquam pretium</h4>
						<p>Aenean ac leo eget nunc fringilla fringilla a non nulla! Nunc orci mi, venenatis quis ultrices vitae, congue non nibh. Nulla bibendum justo eget.</p>
						</div>
						<div class="col-md-4 choose-grid wow fadeInLeft animated" data-wow-delay=".5s">
						<h4><span class="glyphicon glyphicon-zoom-in" aria-hidden="true"></span>Nam aliquam pretium</h4>
						<p>Aenean ac leo eget nunc fringilla fringilla a non nulla! Nunc orci mi, venenatis quis ultrices vitae, congue non nibh. Nulla bibendum justo eget.</p>
						</div>
						<div class="clearfix"></div>
					</div>
				</div>
			</div>
<!-- experts -->
<div class="experts">
	<div class="container">
		<h3 class="tittle">Team</h3>
		<div class="col-md-4 bottom-grid wow fadeInRight animated" data-wow-delay=".5s">
			<div class="btm-right">
				<%= image_tag("team1.jpg", :alt => " ") %>
					<div class="captn">
						<h4>Victoria</h4>
						<a href="#" class="icon_1"></a>
						<a href="#" class="icon_2"></a>
						<a href="#" class="icon_3"></a>
						<a href="#" class="icon_4"></a>		
					</div>
			</div>
		</div>
		<div class="col-md-4 bottom-grid wow fadeInDown animated" data-wow-delay=".5s">
			<div class="btm-right">
				<%= image_tag("team2.jpg", :alt => " ") %>
					<div class="captn">
						<h4>William</h4>
						<a href="#" class="icon_1"></a>
						<a href="#" class="icon_2"></a>
						<a href="#" class="icon_3"></a>
						<a href="#" class="icon_4"></a>		
					</div>
			</div>
		</div>
		<div class="col-md-4 bottom-grid wow fadeInLeft animated" data-wow-delay=".5s">
			<div class="btm-right">
				<%= image_tag("team4.jpg", :alt => " ") %>
					<div class="captn">
						<h4>Federica</h4>
						<a href="#" class="icon_1"></a>
						<a href="#" class="icon_2"></a>
						<a href="#" class="icon_3"></a>
						<a href="#" class="icon_4"></a>		
					</div>
			</div>
		</div>
		<div class="clearfix"></div>
	</div>
</div>
<!-- //experts -->
<!-- //about -->
<!-- contact -->
<div class="contact">
	<div class="container">
		<div class="col-md-4 contact-left wow fadeInRight animated" data-wow-delay=".5s">
			<h3>Address</h3>
			<h2>Ultimate</h2>
			<p>Diamond street,<br>
			260-14 City, Country<br>
			+62 000-0000-00</p>
			<ul>
				<li>Monday - Friday</li>
				<li>Saturday</li>
				<li>Sunday</li>
			</ul>
			<ul>
				<li>8:00 am - 11:00 pm</li>
				<li>10:00 am - 7:00 pm</li>
				<li>10:00 am - 7:00 pm</li>
			</ul>
			<div class="clearfix"></div>
		</div>
		<div class="col-md-4 contact-left wow fadeInUp animated" data-wow-delay=".5s">
			<h3>Links</h3>
			<ul>
				<li><a href="index.html">Home</a></li>
				<li><a href="about.html">About</a></li>
				<li><a href="shortcodes.html">Shortcodes</a></li>
				<li><a href="news.html">News</a></li>
				<li><a href="contact.html">Contact</a></li>
			</ul>
			
		</div>
		<div class="col-md-4 contact-left footer-bottom wow fadeInLeft animated" data-wow-delay=".5s">
			<h3>Signup for Newsletter</h3>
			<form>
					<input type="text" value="Enter your email" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Enter your email';}" required="">
					<input type="submit" value=" ">
			</form>
			<a href="#"><span>Facebook</span></a>
			<a href="#"><span>Pinterest</span></a>
			<a href="#"><span>LinkedIn </span></a>
			<a href="#"><span>Behance</span></a>
		</div>
		<div class="clearfix"></div>
	</div>
</div>
<div class="footer wow fadeInDown animated" data-wow-delay=".5s">
	<div class="container">
		<p> &copy; 2016 Ultimate. All Rights Reserved | Design by  <a href="http://w3layouts.com/"> W3layouts</a></p>
	</div>
</div>
<!-- //contact -->
<!-- for bootstrap working -->
	<script src="js/bootstrap.js"></script>
<!-- //for bootstrap working -->
<!-- smooth scrolling -->
	<script type="text/javascript">
		$(document).ready(function() {
		/*
			var defaults = {
			containerID: 'toTop', // fading element id
			containerHoverID: 'toTopHover', // fading element hover id
			scrollSpeed: 1200,
			easingType: 'linear' 
			};
		*/								
		$().UItoTop({ easingType: 'easeOutQuart' });
		});
	</script>
	<a href="#" id="toTop" style="display: block;"> <span id="toTopHover" style="opacity: 1;"> </span></a>
<!-- //smooth scrolling -->

app/views/contact/contact.html.erb
<div class="view-map">
	<h3 class="tittle">View on map</h3>
	<div class="map wow fadeInUp animated" data-wow-delay=".5s">
		<iframe src="https://www.google.com/maps/embed?pb=!1m10!1m8!1m3!1d2482.432383990807!2d0.028213999961443994!3d51.52362882484525!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sen!2sin!4v1423469959819"></iframe>
	</div>
</div>
<div class="map-grids">
	<div class="container">
		<div class="col-md-3 map-left wow fadeInRight animated" data-wow-delay=".5s">
			<h3>Information</h3>
			<p>Pellentesque ut urna eu mauris scele risque auctor volutpat et massa pers piciis iste natus scele risque auctor volutpat.</p>
		</div>
		<div class="col-md-6 map-middle wow fadeInUp animated" data-wow-delay=".5s">
			<h3>Feedback</h3>
			<form>
					<input type="text" value="Name" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Name';}" required="">
					<input type="text" value="Email" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Email';}" required="">
					<textarea onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Message...';}" required="">Message...</textarea>
					<input type="submit" value="Send" >
			</form>
		</div>
		<div class="col-md-3 map-left wow fadeInLeft animated" data-wow-delay=".5s">
				<div class="call">
					<div class="col-xs-3 contact-grdl">
						<span class="glyphicon glyphicon-phone" aria-hidden="true"></span>
					</div>
					<div class="col-xs-9 contact-grdr">
						<ul>
							<li>+3402 890 679</li>
							<li>+5356 890 679</li>
						</ul>
					</div>
					<div class="clearfix"> </div>
				</div>
				<div class="call">
					<div class="col-xs-3 contact-grdl">
						<span class="glyphicon glyphicon-send" aria-hidden="true"></span>
					</div>
					<div class="col-xs-9 contact-grdr">
						<ul>
							<li>345 Diamond Street,</li>
							<li>Greece.</li>
						</ul>
					</div>
					<div class="clearfix"> </div>
				</div>
				<div class="call">
					<div class="col-xs-3 contact-grdl">
						<span class="glyphicon glyphicon-envelope" aria-hidden="true"></span>
					</div>
					<div class="col-xs-9 contact-grdr">
						<ul>
							<li><a href="mailto:info@example.com">info@example.com</a></li>
						</ul>
					</div>
					<div class="clearfix"> </div>
				</div>

		</div>
		<div class="clearfix"></div>
	</div>
</div>
<!-- //map -->
<!-- contact -->
<div class="contact">
	<div class="container">
		<div class="col-md-4 contact-left wow fadeInRight animated" data-wow-delay=".5s">
			<h3>Address</h3>
			<h2>Ultimate</h2>
			<p>Diamond street,<br>
			260-14 City, Country<br>
			+62 000-0000-00</p>
			<ul>
				<li>Monday - Friday</li>
				<li>Saturday</li>
				<li>Sunday</li>
			</ul>
			<ul>
				<li>8:00 am - 11:00 pm</li>
				<li>10:00 am - 7:00 pm</li>
				<li>10:00 am - 7:00 pm</li>
			</ul>
			<div class="clearfix"></div>
		</div>
		<div class="col-md-4 contact-left wow fadeInUp animated" data-wow-delay=".5s">
			<h3>Links</h3>
			<ul>
				<li><a href="index.html">Home</a></li>
				<li><a href="about.html">About</a></li>
				<li><a href="shortcodes.html">Shortcodes</a></li>
				<li><a href="news.html">News</a></li>
				<li><a href="contact.html">Contact</a></li>
			</ul>
			
		</div>
		<div class="col-md-4 contact-left footer-bottom wow fadeInLeft animated" data-wow-delay=".5s">
			<h3>Signup for Newsletter</h3>
			<form>
					<input type="text" value="Enter your email" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Enter your email';}" required="">
					<input type="submit" value=" ">
			</form>
			<a href="#"><span>Facebook</span></a>
			<a href="#"><span>Pinterest</span></a>
			<a href="#"><span>LinkedIn </span></a>
			<a href="#"><span>Behance</span></a>
		</div>
		<div class="clearfix"></div>
	</div>
</div>
<div class="footer wow fadeInDown animated" data-wow-delay=".5s">
	<div class="container">
		<p> &copy; 2016 Ultimate. All Rights Reserved | Design by  <a href="http://w3layouts.com/"> W3layouts</a></p>
	</div>
</div>
<!-- //contact -->
<!-- for bootstrap working -->
	<script src="js/bootstrap.js"></script>
<!-- //for bootstrap working -->
<!-- smooth scrolling -->
	<script type="text/javascript">
		$(document).ready(function() {
		/*
			var defaults = {
			containerID: 'toTop', // fading element id
			containerHoverID: 'toTopHover', // fading element hover id
			scrollSpeed: 1200,
			easingType: 'linear' 
			};
		*/								
		$().UItoTop({ easingType: 'easeOutQuart' });
		});
	</script>
	<a href="#" id="toTop" style="display: block;"> <span id="toTopHover" style="opacity: 1;"> </span></a>
<!-- //smooth scrolling -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Penzi</title>
    <%= csrf_meta_tags %>
 <!--  included stylesheets -->
    <%= stylesheet_link_tag   'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'animate.css' %>
    <%= stylesheet_link_tag 'component.css' %>
    <%= stylesheet_link_tag 'hover_pack.css' %>
    <%= stylesheet_link_tag 'style.css' %>

 <!-- included js external sheets -->
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'hover_pack.js' %>
    <%= javascript_include_tag 'easing.js' %>
    <%= javascript_include_tag 'wow.min.js' %>
    <%= javascript_include_tag 'move-top.js' %>

    <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false);
	function hideURLbar(){ window.scrollTo(0,1); } </script>

		<script type="text/javascript">
					jQuery(document).ready(function($) {
						$(".scroll").click(function(event){		
							event.preventDefault();
							$('html,body').animate({scrollTop:$(this.hash).offset().top},1000);
						});
					});
				</script>
  </head>

  <body>
  <!-- banner -->

	<div class="container">
		<div class="header-nav wow fadeInDown animated" data-wow-delay=".5s">
						<nav class="navbar navbar-default">
							<!-- Brand and toggle get grouped for better mobile display -->
							<div class="navbar-header logo">
								<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
									<span class="sr-only">Toggle navigation</span>
									<span class="icon-bar"></span>
									<span class="icon-bar"></span>
									<span class="icon-bar"></span>
								</button>
								<h1>
									<a class="navbar-brand link link--yaku" href="index.html"><span>U</span><span>l</span><span>t</span><span>i</span><span>m</span><span>a</span><span>t</span><span>e</span></a>
								</h1>
								
							</div>
							<!-- Collect the nav links, forms, and other content for toggling -->
							<div class="collapse navbar-collapse nav-wil" id="bs-example-navbar-collapse-1">
								<nav class="cl-effect-1">
									<ul class="nav navbar-nav ">
									  <li><%= link_to "Home", root_path ,:class => "hvr-overline-from-left button2 active" %></li>
										<li><%= link_to "About", about_about_path ,:class => "hvr-overline-from-left button2" %></li>
										<li><%= link_to "Blog", root_path ,:class => "hvr-overline-from-left button2" %></li>
										<li><%= link_to "Gallery", gallery_gallery_path ,:class => "hvr-overline-from-left button2" %></li>
										<li><%= link_to "News", news_news_path ,:class => "hvr-overline-from-left button2" %></li>
										<li><%= link_to "Contact", contact_contact_path ,:class => "hvr-overline-from-left button2" %></li>
									</ul>
								</nav>
							</div><!-- /navbar-collapse -->
						</nav>
		</div>
	</div>
    <%= yield %>
  </body>
</html>

app/views/news/news.html.erb
<!-- events -->
<div class="events-sec">
	 <div class="container">
		 <h3 class="tittle" >Events</h3>
		 <div class="event-grids">			
		     <div class="col-md-4 event-grid wow fadeInRight animated" data-wow-delay=".5s">
				 <div class="date">
				     <h4>26</h4>
					 <span>08/2012</span>
				 </div>				 
			     <div class="event-info">
					  <h4><a href="single.html">Etiam malesu feugiat.</a></h4>
						<p>Praesent sagittis in enim vel cursus. Aenean velit ante, maximus ac placerat at, 
						volutpat et orci. Aliquam eu tellus orci.</p>					
				 </div>
				 <div class="clearfix"></div>				 			 
			 </div>
			 <div class="col-md-4 event-grid wow fadeInRight animated" data-wow-delay=".5s">
				 <div class="date">
				     <h4>24</h4>
					 <span>06/2012</span>
				 </div>				 
			     <div class="event-info">
					  <h4><a href="single.html">Etiam malesu feugiat.</a></h4>
						<p>Praesent sagittis in enim vel cursus. Aenean velit ante, maximus ac placerat at, 
						volutpat et orci. Aliquam eu tellus orci.</p>					
				 </div>
				 <div class="clearfix"></div>				 			 
			 </div>
			 <div class="col-md-4 event-grid wow fadeInRight animated" data-wow-delay=".5s">
				 <div class="date">
				     <h4>20</h4>
					 <span>04/2012</span>
				 </div>				 
			     <div class="event-info">
					  <h4><a href="single.html">Etiam malesu feugiat.</a></h4>
						<p>Praesent sagittis in enim vel cursus. Aenean velit ante, maximus ac placerat at, 
						volutpat et orci. Aliquam eu tellus orci.</p>					
				 </div>
				 <div class="clearfix"></div>				 			 
			 </div>	
		 		
		     <div class="col-md-4 event-grid wow fadeInLeft animated" data-wow-delay=".5s">
				 <div class="date">
				     <h4>19</h4>
					 <span>08/2012</span>
				 </div>				 
			     <div class="event-info">
					  <h4><a href="single.html">Etiam malesu feugiat.</a></h4>
						<p>Praesent sagittis in enim vel cursus. Aenean velit ante, maximus ac placerat at, 
						volutpat et orci. Aliquam eu tellus orci.</p>					
				 </div>
				 <div class="clearfix"></div>				 			 
			 </div>
			 <div class="col-md-4 event-grid wow fadeInLeft animated" data-wow-delay=".5s">
				 <div class="date">
				     <h4>22</h4>
					 <span>05/2012</span>
				 </div>				 
			     <div class="event-info">
					  <h4><a href="single.html">Etiam malesu feugiat.</a></h4>
						<p>Praesent sagittis in enim vel cursus. Aenean velit ante, maximus ac placerat at, 
						volutpat et orci. Aliquam eu tellus orci.</p>					
				 </div>
				 <div class="clearfix"></div>				 			 
			 </div>
			 <div class="col-md-4 event-grid wow fadeInLeft animated" data-wow-delay=".5s">
				 <div class="date">
				     <h4>25</h4>
					 <span>03/2012</span>
				 </div>				 
			     <div class="event-info">
					  <h4><a href="single.html">Etiam malesu feugiat.</a></h4>
						<p>Praesent sagittis in enim vel cursus. Aenean velit ante, maximus ac placerat at, 
						volutpat et orci. Aliquam eu tellus orci.</p>					
				 </div>
				 <div class="clearfix"></div>				 			 
			 </div>
			 <div class="clearfix"></div>	
		</div>	
	 </div>
</div>
<!-- //events -->
<!-- news -->
	<div class="news">
		<div class="container">
			<div class="news-text">
				<h3>Latest news</h3>
				<p>Repellat earum rerum hic tenetur a sapiente delectus, 
				ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis 
				doloribus asperiores repellat.</p>
			</div>
			<div class="news-grids">
				<div class="col-md-3 news-grid mask wow fadeInRight animated" data-wow-delay=".5s">
					<a href="single.html" class="mask"><%= image_tag("pic1.jpg", :class => "img-responsive zoom-img", :alt => "image") %></a>
					<span>JUN 10,2014</span>
					<div class="news-info">
						<h4><a href="single.html">Repellat earumrerum</a></h4>
						<p>Pellentesque ut urna eu mauris scele risque auctor volutpat et massa pers piciis iste natus scele risque auctor volutpat et massa.</p>
						<a href="single.html">Readmore</a>
					</div>
				</div>
				<div class="col-md-3 news-grid mask wow fadeInRight animated" data-wow-delay=".5s">
					<a href="single.html" class="mask"><%= image_tag("pic2.jpg", :class => "img-responsive zoom-img" ,:alt => "image") %></a>
					<span>JAN 15,2015</span>
					<div class="news-info">
						<h4><a href="single.html">Repellat earumrerum</a></h4>
						<p>Pellentesque ut urna eu mauris scele risque auctor volutpat et massa pers piciis iste natus scele risque auctor volutpat et massa.</p>
						<a href="single.html">Readmore</a>
					</div>
				</div>
				<div class="col-md-3 news-grid mask wow fadeInLeft animated" data-wow-delay=".5s">
					<a href="single.html" class="mask"><%= image_tag("pic5.jpg" ,:class => "img-responsive zoom-img", :alt => "image") %></a>
					<span>JUN 10,2015</span>
					<div class="news-info">
						<h4><a href="single.html">Repellat earumrerum</a></h4>
						<p>Pellentesque ut urna eu mauris scele risque auctor volutpat et massa pers piciis iste natus scele risque auctor volutpat et massa.</p>
						<a href="single.html">Readmore</a>
					</div>
				</div>
				<div class="col-md-3 news-grid mask wow fadeInLeft animated" data-wow-delay=".5s">
					<a href="single.html" class="mask"><%= image_tag("pic4.jpg", :class => "img-responsive zoom-img", :alt => "image") %></a>
					<span>APR 30,2015</span>
					<div class="news-info">
						<h4><a href="single.html">Repellat earumrerum</a></h4>
						<p>Pellentesque ut urna eu mauris scele risque auctor volutpat et massa pers piciis iste natus scele risque auctor volutpat et massa.</p>
						<a href="single.html">Readmore</a>
					</div>
				</div>
				<div class="clearfix"> </div>
			</div>
		</div>
	</div>
<!-- //news -->
<!-- contact -->
<div class="contact">
	<div class="container">
		<div class="col-md-4 contact-left wow fadeInRight animated" data-wow-delay=".5s">
			<h3>Address</h3>
			<h2>Ultimate</h2>
			<p>Diamond street,<br>
			260-14 City, Country<br>
			+62 000-0000-00</p>
			<ul>
				<li>Monday - Friday</li>
				<li>Saturday</li>
				<li>Sunday</li>
			</ul>
			<ul>
				<li>8:00 am - 11:00 pm</li>
				<li>10:00 am - 7:00 pm</li>
				<li>10:00 am - 7:00 pm</li>
			</ul>
			<div class="clearfix"></div>
		</div>
		<div class="col-md-4 contact-left wow fadeInUp animated" data-wow-delay=".5s">
			<h3>Links</h3>
			<ul>
				<li><a href="index.html">Home</a></li>
				<li><a href="about.html">About</a></li>
				<li><a href="shortcodes.html">Shortcodes</a></li>
				<li><a href="news.html">News</a></li>
				<li><a href="contact.html">Contact</a></li>
			</ul>
			
		</div>
		<div class="col-md-4 contact-left footer-bottom wow fadeInLeft animated" data-wow-delay=".5s">
			<h3>Signup for Newsletter</h3>
			<form>
					<input type="text" value="Enter your email" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Enter your email';}" required="">
					<input type="submit" value=" ">
			</form>
			<a href="#"><span>Facebook</span></a>
			<a href="#"><span>Pinterest</span></a>
			<a href="#"><span>LinkedIn </span></a>
			<a href="#"><span>Behance</span></a>
		</div>
		<div class="clearfix"></div>
	</div>
</div>
<div class="footer wow fadeInDown animated" data-wow-delay=".5s">
	<div class="container">
		<p> &copy; 2016 Ultimate. All Rights Reserved | Design by  <a href="http://w3layouts.com/"> W3layouts</a></p>
	</div>
</div>
<!-- //contact -->
<!-- for bootstrap working -->
	<script src="js/bootstrap.js"></script>
<!-- //for bootstrap working -->
<!-- smooth scrolling -->
	<script type="text/javascript">
		$(document).ready(function() {
		/*
			var defaults = {
			containerID: 'toTop', // fading element id
			containerHoverID: 'toTopHover', // fading element hover id
			scrollSpeed: 1200,
			easingType: 'linear' 
			};
		*/								
		$().UItoTop({ easingType: 'easeOutQuart' });
		});
	</script>
	<a href="#" id="toTop" style="display: block;"> <span id="toTopHover" style="opacity: 1;"> </span></a>
<!-- //smooth scrolling -->